language: node_js
env:
  global:
  - CXX=g++-4.8
before_install:
- ./scripts/ensure-compatible-npm.sh
script: travis_retry npm test
node_js:
- '5'
- '4'
- 'iojs'
- '0.12'
- '0.11'
- '0.10'
- '0.8'
sudo: false
addons:
  sauce_labs:
    username: dasilvacontin
    access_key:
      secure: NQyRY/F4fDVrACSSKlk0k1Y2BDaS5RlqqeozEMxkL60MINU8ALBYcYRGmupdnV7wrU9joNtMCu3eSq91X8STbvON7PJLNcx/yyIx6+nfHDpRBV1p03yY3+q1fi7mZKgRX6fHj3/kuNezbafJujg2HflmrpdpZ3kyPxRo3gUMkJQ=
notifications:
  urls:
    - secure: EmycFlk48bUvOQ07mxnbcn6T+n3G4wVWuXgrDsUUp6EhJ9866wQK9i+qVhqogWuSEQrGoVaS/vpc/NEYxDP30BD/+nqgvOhVhLVEgtziI85imyV/oUVpArdW3AUmuzCrx7rQCivygjpBmWV9ZcUT5Km4qp1iQhuumy2WbplxrZ4=
  on_success: change
  on_failure: always
